### ISSUE TITLE
Missing xml2gff

### ISSUE THREAD

**Issue by Aqvilinus** [xoreos/xoreos-tools#51]
Hi, @DrMcCoy!

Is **xml2gff** tool still under development? I can see [its source code](https://github.com/xoreos/xoreos-tools/blob/master/src/xml2gff.cpp), but can't find it anywhere in the release bundles.

**Comment by DrMcCoy** [comment]
Ah, yes. It's not in the latest release bundle, because it was added after the latest release. Sorry about that. You can, of course, always compile the xoreos-tools yourself, though I'm aware that's not for everyone.

The xml2gff tool will be in the next release, which I am planning for this month (coinciding with the 10th anniversary of the xoreos project).
